(ns geoutils.locations
  (:gen-class)
  (:require [geoutils.geographicposition :as gp] )
)

;;;
;;; Special Places
;;;

(def northpole-primemeridian (gp/geographic-position  90.0   0.0))
(def northpole-intldateline  (gp/geographic-position  90.0 180.0))
(def southpole-primemeridian (gp/geographic-position -90.0   0.0))
(def southpole-intldateline  (gp/geographic-position -90.0 180.0))
(def equator-primemeridian   (gp/geographic-position   0.0   0.0))

;;;
;;; Testing Locations
;;;
(def equatorPM   (gp/geographic-position   0.0   0.0))
(def equator90E  (gp/geographic-position   0.0  90.0))
(def equator90W  (gp/geographic-position   0.0 -90.0))
(def north40PM   (gp/geographic-position  40.0   0.0))
(def south40PM   (gp/geographic-position -40.0   0.0))
(def equator60E  (gp/geographic-position   0.0  60.0))
(def equator60W  (gp/geographic-position   0.0 -60.0))


;;;
;;;  Major Cities - USA
;;;
(def Anchorage-AK       (assoc (gp/geographic-position 61.22   149.85) :name "Anchorage, AK"))
(def Angoon-AK          (assoc (gp/geographic-position 57.83   134.97) :name "Angoon, AK"))
(def Aniak-AK           (assoc (gp/geographic-position 61.58   159.53) :name "Aniak, AL"))
(def Atlanta-GA         (assoc (gp/geographic-position 33.763 -84.422) :name "Atlanta, GA"))
(def AtlanticCity-NJ    (assoc (gp/geographic-position 39.380 -74.453) :name "Atlantic City, NJ"))
(def Austin-TX          (assoc (gp/geographic-position 30.300 -97.752) :name "Austin, TX"))
(def Baltimore-MD       (assoc (gp/geographic-position 39.305 -76.614) :name "Baltimore, MD"))
(def Barrow-AK          (assoc (gp/geographic-position 71.30   156.78) :name "Barrow, AK"))
(def Boston-MA          (assoc (gp/geographic-position 42.319 -71.085) :name "Boston, MA"))
(def Bronx-NY           (assoc (gp/geographic-position 40.850 -73.866) :name "Bronx, NY"))
(def Brooklyn-NY        (assoc (gp/geographic-position 40.650 -73.950) :name "Brooklyn, NY"))
(def Charlotte-NC       (assoc (gp/geographic-position 35.208 -80.830) :name "Charlotte, NC"))
(def Chicago-IL         (assoc (gp/geographic-position 41.837 -87.686) :name "Chicago, IL"))
(def Cincinnati-OH      (assoc (gp/geographic-position 39.141 -84.506) :name "Cincinnati, OH"))
(def Cleveland-OH       (assoc (gp/geographic-position 41.477 -81.680) :name "Cleveland, OH"))
(def Columbus-OH        (assoc (gp/geographic-position 39.986 -82.985) :name "Columbus, OH"))
(def Dallas-TX          (assoc (gp/geographic-position 32.794 -96.766) :name "Dallas, TX"))
(def Denver-CO          (assoc (gp/geographic-position 39.762 -104.876) :name "Denver, CO"))
(def Detroit-MI         (assoc (gp/geographic-position 42.383 -83.102) :name "Detroit, MI"))
(def DutchHarbor-AK     (assoc (gp/geographic-position 53.88   166.53) :name "Dutch Harbor, AK"))
(def Fairbanks-AK       (assoc (gp/geographic-position 64.82   147.87) :name "Fairbanks, AK"))
(def FortYukon-AK       (assoc (gp/geographic-position 66.57   145.27) :name "Fort Yukon, AK"))
(def Hilo-HI            (assoc (gp/geographic-position 19.72   155.07) :name "Hilo, HI"))
(def Honolulu-HI        (assoc (gp/geographic-position 21.35   157.93) :name "Honolulu, HI"))
(def Houston-TX         (assoc (gp/geographic-position 29.786 -95.389) :name "Houston, TX"))
(def Indianapolis-IN    (assoc (gp/geographic-position 39.777 -86.146) :name "Indianapolis, IN"))
(def Jacksonville-FL    (assoc (gp/geographic-position 30.332 -81.675) :name "Jacksonville, FL"))
(def Juneau-AK          (assoc (gp/geographic-position 58.37   134.58) :name "Juneau, AK"))
(def Kahului-HI         (assoc (gp/geographic-position 20.90   156.43) :name "Kahului, HI"))
(def KansasCity-MO      (assoc (gp/geographic-position 39.124 -94.554) :name "Kansas City, MO"))
(def Kenai-AK           (assoc (gp/geographic-position 60.57   151.25) :name "Kenai, AK"))
(def Ketchikan-AK       (assoc (gp/geographic-position 55.35   131.70) :name "Ketchikan, AK"))
(def KilaueaPt-HI       (assoc (gp/geographic-position 22.38   159.67) :name "Kilauea Pt, HI"))
(def Kodiak-AK          (assoc (gp/geographic-position 57.75   152.50) :name "Kodiak, AK"))
(def Lanai-HI           (assoc (gp/geographic-position 20.80   156.95) :name "Lanai, HI"))
(def LasVegas-NV        (assoc (gp/geographic-position 36.233 -115.265) :name "Las Vegas, NV"))
(def LosAngeles-CA      (assoc (gp/geographic-position 34.114 -118.407) :name "Los Angeles, CA"))
(def Louisville-KY      (assoc (gp/geographic-position 38.166 -85.649) :name "Louisville, KY"))
(def Maui-HI            (assoc (gp/geographic-position 20.97   156.83) :name "Maui, HI"))
(def Memphis-TN         (assoc (gp/geographic-position 35.105 -89.977) :name "Memphis, TN"))
(def Miami-FL           (assoc (gp/geographic-position 25.784 -80.210) :name "Miami, FL"))
(def Milwaukee-WI       (assoc (gp/geographic-position 43.064 -87.967) :name "Milwaukee, WI"))
(def Minneapolis-MN     (assoc (gp/geographic-position 44.964 -93.268) :name "Minneapolis, MN"))
(def Molokai-HI         (assoc (gp/geographic-position 21.15   157.10) :name "Molokai, HI"))
(def Nashville-TN       (assoc (gp/geographic-position 36.172 -86.784) :name "Nashville, TN"))
(def Nenana-AK          (assoc (gp/geographic-position 64.55   149.08) :name "Nenana, AK"))
(def NewOrleans-LA      (assoc (gp/geographic-position 30.069 -89.929) :name "New Orleans, LA"))
(def NewYork-NY         (assoc (gp/geographic-position 40.694 -73.925) :name "New York, NY"))
(def Nome-AK            (assoc (gp/geographic-position 64.50   165.43) :name "Nome, AK"))
(def Orlando-FL         (assoc (gp/geographic-position 28.477 -81.337) :name "Orlando, FL"))
(def Philadelphia-PA    (assoc (gp/geographic-position 40.008 -75.134) :name "Philadelphia, PA"))
(def Phoenix-AZ         (assoc (gp/geographic-position 33.572 -112.089) :name "Phoenix, AZ"))
(def Pittsburgh-PA      (assoc (gp/geographic-position 40.440 -79.976) :name "Pittsburgh, PA"))
(def Portland-OR        (assoc (gp/geographic-position 45.537 -122.650) :name "Portland, OR"))
(def Providence-RI      (assoc (gp/geographic-position 41.823 -71.419) :name "Providence, RI"))
(def PrudhoeBay-AK      (assoc (gp/geographic-position 70.25   148.33) :name "Prudhoe Bay, AK"))
(def Raleigh-NC         (assoc (gp/geographic-position 35.833 -78.644) :name "Raleigh, NC"))
(def Richmond-VA        (assoc (gp/geographic-position 37.530 -77.476) :name "Richmond, VA"))
(def Sacramento-CA      (assoc (gp/geographic-position 38.567 -121.468) :name "Sacramento, CA"))
(def SaltLakeCity-UT    (assoc (gp/geographic-position 40.778 -111.931) :name "Salt Lake City, UT"))
(def SanAntonio-TX      (assoc (gp/geographic-position 29.466 -98.525) :name "San Antonio, TX"))
(def SanDiego-CA        (assoc (gp/geographic-position 32.831 -117.123) :name "San Diego, CA"))
(def SanFrancisco-CA    (assoc (gp/geographic-position 37.756 -122.443) :name "San Francisco, CA"))
(def SanJose-CA         (assoc (gp/geographic-position 37.302 -121.849) :name "San Jose, CA"))
(def Seattle-WA         (assoc (gp/geographic-position 47.621 -122.324) :name "Seattle, WA"))
(def Seward-AK          (assoc (gp/geographic-position 60.18   149.75) :name "Seward, AK"))
(def Sitka-AK           (assoc (gp/geographic-position 57.07   135.35) :name "Sitka, AK"))
(def Skagway-AK         (assoc (gp/geographic-position 59.75   135.53) :name "Skagway, AK"))
(def StLouis-MO         (assoc (gp/geographic-position 38.636 -90.245) :name "St Louis, MO"))
(def Talkeetna-AK       (assoc (gp/geographic-position 62.30   150.10) :name "Talkeetna, AK"))
(def Tampa-FL           (assoc (gp/geographic-position 27.994 -82.445) :name "Tampa, FL"))
(def Umiat-AK           (assoc (gp/geographic-position 69.37   152.13) :name "Umiat, AK"))
(def VirginiaBeach-VA   (assoc (gp/geographic-position 36.734 -76.044) :name "Virginia Beach, VA"))
(def Waimea-HI          (assoc (gp/geographic-position 20.00   156.12) :name "Waimea, HI"))
(def Washington-DC      (assoc (gp/geographic-position 38.905 -77.016) :name "Washington, DC"))
(def WestPalmBeach-FL   (assoc (gp/geographic-position 26.709 -80.064) :name "West Palm Beach, FL"))
(def Whittier-AK        (assoc (gp/geographic-position 60.78   148.72) :name "Whittier, AK"))


;;;
;;; Major Cities World
;;;
(def Aberdeen-UK        (assoc (gp/geographic-position   57.150   -2.150) :name "Aberdeen, Scotland"))
(def Adelaide-AU        (assoc (gp/geographic-position  -34.917  138.600) :name "Adelaide, Australia"))
(def Algiers-DZ         (assoc (gp/geographic-position   36.833    3.000) :name "Algiers, Morocco"))
(def Amsterdam-NL       (assoc (gp/geographic-position   52.367    4.883) :name "Amsterdam, Netherlands"))
(def Ankara-TR          (assoc (gp/geographic-position   39.917   32.917) :name "Ankara, Turkey"))
(def Asuncin-PY         (assoc (gp/geographic-position  -25.250  -57.667) :name "Asuncin, Paraguay"))
(def Athens-GR          (assoc (gp/geographic-position   37.967   23.717) :name "Athens, Greece"))
(def Auckland-NZ        (assoc (gp/geographic-position  -36.867  174.750) :name "Auckland, New Zealand"))
(def Bangkok-TH         (assoc (gp/geographic-position   13.750  100.500) :name "Bangkok, Thailand"))
(def Barcelona-ES       (assoc (gp/geographic-position   41.383    2.150) :name "Barcelona, Spain"))
(def Beijing-CN         (assoc (gp/geographic-position   39.917  116.417) :name "Beijing, China"))
(def Belfast-UK         (assoc (gp/geographic-position   54.617   -5.933) :name "Belfast, North Ireland"))
(def Belgrade-RS        (assoc (gp/geographic-position   44.867   20.533) :name "Belgrade, Serbia"))
(def Belm-BR            (assoc (gp/geographic-position   -1.467  -48.483) :name "Belm, Germany"))
(def Berlin-DE          (assoc (gp/geographic-position   52.500   13.417) :name "Berlin, Germany"))
(def Birmingham-UK      (assoc (gp/geographic-position   52.417   -1.917) :name "Birmingham, England"))
(def Bogota-CO          (assoc (gp/geographic-position    4.533  -74.250) :name "Bogota, Columbia"))
(def Bombay-IN          (assoc (gp/geographic-position   19.000   72.800) :name "Bombay, India"))
(def Bordeaux-FR        (assoc (gp/geographic-position   44.833   -0.517) :name "Bordeaux, France"))
(def Bremen-DE          (assoc (gp/geographic-position   53.083    8.817) :name "Bremen, Germany"))
(def Brisbane-AU        (assoc (gp/geographic-position  -27.483  153.133) :name "Brisbane, Australia"))
(def Bristol-UK         (assoc (gp/geographic-position   51.467   -2.583) :name "Bristol, England"))
(def Brussels-BE        (assoc (gp/geographic-position   50.867    4.367) :name "Brussels, Belgim"))
(def Bucharest-RO       (assoc (gp/geographic-position   44.417   26.117) :name "Bucharest, Romania"))
(def Budapest-HU        (assoc (gp/geographic-position   47.500   19.083) :name "Budapest, Hungary"))
(def BuenosAires-AR     (assoc (gp/geographic-position  -34.583  -58.367) :name "BuenosAires, Argentina"))
(def Cairo-EG           (assoc (gp/geographic-position   30.033   31.350) :name "Cairo, Egypt"))
(def Calcutta-IN        (assoc (gp/geographic-position   22.567   88.400) :name "Calcutta, India"))
(def Canton-CN          (assoc (gp/geographic-position   23.117  113.250) :name "Canton, China"))
(def Capetown-ZA        (assoc (gp/geographic-position  -33.917   18.367) :name "Capetown, South Africa"))
(def Caracas-VE         (assoc (gp/geographic-position   10.467  -67.033) :name "Caracas, Venezuela"))
(def Chihuahua-MX       (assoc (gp/geographic-position   28.617 -106.083) :name "Chihuahua, Mexico"))
(def Chongqing-CN       (assoc (gp/geographic-position   29.767  106.567) :name "Chongqing, China"))
(def Copenhagen-DK      (assoc (gp/geographic-position   55.667   12.567) :name "Copenhagen, Denmark"))
(def Crdoba-AR          (assoc (gp/geographic-position  -31.467  -64.167) :name "Crdoba, Argentina"))
(def Dakar-SN           (assoc (gp/geographic-position   14.667  -17.467) :name "Dakar, Senegal"))
(def Darwin-AU          (assoc (gp/geographic-position  -12.467  130.850) :name "Darwin, Australia"))
(def Djibouti-DJ        (assoc (gp/geographic-position   11.500   43.050) :name "Djibouti, Djibouti"))
(def Dublin-IE          (assoc (gp/geographic-position   53.333   -6.250) :name "Dublin, Ireland"))
(def Durban-ZA          (assoc (gp/geographic-position  -29.883   30.883) :name "Durban, South Africa"))
(def Edinburgh-UK       (assoc (gp/geographic-position   55.917   -3.167) :name "Edinburgh, Scotland"))
(def Frankfurt-DE       (assoc (gp/geographic-position   50.117    8.683) :name "Frankfurt, Germany"))
(def Georgetown-GY      (assoc (gp/geographic-position    6.750  -58.250) :name "Georgetown, Guiana"))
(def Glasgow-UK         (assoc (gp/geographic-position   55.833   -4.250) :name "Glasgow, Scotland"))
(def Greenwich-UK       (assoc (gp/geographic-position   51.493    0.0)   :name "Greenwich, England"))
(def GuatemalaCity-GT   (assoc (gp/geographic-position   14.617  -90.517) :name "Guatemala City, Guatemala"))
(def Guayaquil-EC       (assoc (gp/geographic-position   -2.167  -79.933) :name "Guayaquil, Ecuador"))
(def Hamburg-DE         (assoc (gp/geographic-position   53.550   10.033) :name "Hamburg, Germany"))
(def Hammerfest-NO      (assoc (gp/geographic-position   70.633   23.633) :name "Hammerfest, Norway"))
(def Havana-CU          (assoc (gp/geographic-position   23.133  -82.383) :name "Havana, Cuba"))
(def Helsinki-FI        (assoc (gp/geographic-position   60.167   25.000) :name "Helsinki, Finland"))
(def Hobart-AU          (assoc (gp/geographic-position  -42.867  147.317) :name "Hobart, Australia"))
(def HongKong-CN        (assoc (gp/geographic-position   22.333  114.183) :name "HongKong, China"))
(def Iquique-CL         (assoc (gp/geographic-position  -20.167  -70.117) :name "Iquique, Chile"))
(def Irkutsk-RU         (assoc (gp/geographic-position   52.500  104.333) :name "Irkutsk, Russia"))
(def Jakarta-ID         (assoc (gp/geographic-position   -6.267  106.800) :name "Jakarta, Indonesia"))
(def Johannesburg-ZA    (assoc (gp/geographic-position  -26.200   28.067) :name "Johannesburg, South Africa"))
(def Kingston-JM        (assoc (gp/geographic-position   17.983  -76.817) :name "Kingston, Jamaica"))
(def Kinshasa-CG        (assoc (gp/geographic-position   -4.300   15.283) :name "Kinshasa, Congo"))
(def KualaLumpur-MY     (assoc (gp/geographic-position    3.133  101.700) :name "Kuala Lumpur, Malasia"))
(def Lapaz-BO           (assoc (gp/geographic-position  -16.450  -68.367) :name "La Paz, Bolivia"))
(def Leeds-UK           (assoc (gp/geographic-position   53.750   -1.500) :name "Leeds, England"))
(def Lima-PE            (assoc (gp/geographic-position  -12.000  -77.033) :name "Lima, Peru"))
(def Lisbon-PT          (assoc (gp/geographic-position   38.733   -9.150) :name "Lisbon, Portugal"))
(def Liverpool-UK       (assoc (gp/geographic-position   53.417   -3.000) :name "Liverpool, England"))
(def London-UK          (assoc (gp/geographic-position   51.533   -0.083) :name "London, England"))
(def Lyons-FR           (assoc (gp/geographic-position   45.750    4.833) :name "Lyons, France"))
(def Madrid-ES          (assoc (gp/geographic-position   40.433   -3.700) :name "Madrid, Spain"))
(def Manchester-UK      (assoc (gp/geographic-position   53.500   -2.250) :name "Manchester, England"))
(def Marseilles-FR      (assoc (gp/geographic-position   43.333    5.333) :name "Marseilles, France"))
(def Mazatln-MX         (assoc (gp/geographic-position   23.200 -106.417) :name "Mazatln, Mexico"))
(def Mecca-SA           (assoc (gp/geographic-position   21.483   39.750) :name "Mecca, Saudi Arabia"))
(def Melbourne-AU       (assoc (gp/geographic-position  -37.783  144.967) :name "Melbourne, Australia"))
(def MexicoCity-MX      (assoc (gp/geographic-position   19.433  -99.117) :name "MexicoCity, Mexico"))
(def Milan-IT           (assoc (gp/geographic-position   45.450    9.167) :name "Milan, Italy"))
(def MonteVideo-UY      (assoc (gp/geographic-position  -34.883  -56.167) :name "MonteVideo, Uruguay"))
(def Moscow-RU          (assoc (gp/geographic-position   55.750   37.600) :name "Moscow, Russia"))
(def Munich-DE          (assoc (gp/geographic-position   48.133   11.583) :name "Munich, Germany"))
(def Nagasaki-JP        (assoc (gp/geographic-position   32.800  129.950) :name "Nagasaki, Japan"))
(def Nagoya-JP          (assoc (gp/geographic-position   35.117  136.933) :name "Nagoya, Japan"))
(def Nairobi-KE         (assoc (gp/geographic-position   -1.417   36.917) :name "Nairobi, Kenya"))
(def Nanjing-CN         (assoc (gp/geographic-position   32.050  118.883) :name "Nanjing, China"))
(def Naples-IT          (assoc (gp/geographic-position   40.833   14.250) :name "Naples, Italy"))
(def NewDelhi-IN        (assoc (gp/geographic-position   28.583   77.200) :name "NewDelhi, India"))
(def Odessa-UA          (assoc (gp/geographic-position   46.450   30.800) :name "Odessa, Ukraine"))
(def Osaka-JP           (assoc (gp/geographic-position   34.533  135.500) :name "Osaka, Japan"))
(def Oslo-NO            (assoc (gp/geographic-position   59.950   10.700) :name "Oslo, Norway"))
(def PanamaCity-PA      (assoc (gp/geographic-position    8.967  -79.533) :name "Panama City, Panama"))
(def Paramaribo-SR      (assoc (gp/geographic-position    5.750  -55.250) :name "Paramaribo, Suriname"))
(def Paris-FR           (assoc (gp/geographic-position   48.800    2.333) :name "Paris, France"))
(def Perth-AU           (assoc (gp/geographic-position  -31.950  115.867) :name "Perth, Australia"))
(def Plymouth-UK        (assoc (gp/geographic-position   50.417   -4.083) :name "Plymouth, England"))
(def PortMoresby-PG     (assoc (gp/geographic-position   -9.417  147.133) :name "Port Moresby, Papua New Guinea"))
(def Prague-CZ          (assoc (gp/geographic-position   50.083   14.433) :name "Prague, Czech Republic"))
(def Rangoon-MM         (assoc (gp/geographic-position   16.833   96.000) :name "Rangoon, Myanmar"))
(def Reykjavk-IS        (assoc (gp/geographic-position   64.067  -21.967) :name "Reykjavk, Iceland"))
(def RioDeJaneiro-BR    (assoc (gp/geographic-position  -22.950  -43.200) :name "RioDeJaneiro, Brazil"))
(def Rome-IT            (assoc (gp/geographic-position   41.900   12.450) :name "Rome, Italy"))
(def Salvador-BR        (assoc (gp/geographic-position  -12.933  -38.450) :name "Salvador, Brazil"))
(def Santiago-CL        (assoc (gp/geographic-position  -33.467  -70.750) :name "Santiago, Chile"))
(def Shanghai-CN        (assoc (gp/geographic-position   31.167  121.467) :name "Shanghai, China"))
(def Singapore-SG       (assoc (gp/geographic-position    1.233  103.917) :name "Singapore, Singapore"))
(def Sopaulo-BR         (assoc (gp/geographic-position  -23.517  -46.517) :name "Sopaulo, Brazil"))
(def Sofia-BG           (assoc (gp/geographic-position   42.667   23.333) :name "Sofia, Bulgaria"))
(def StPetersburg-RU    (assoc (gp/geographic-position   59.933   30.300) :name "StPetersburg, Russia"))
(def Stockholm-SE       (assoc (gp/geographic-position   59.283   18.050) :name "Stockholm, Sweden"))
(def Sydney-AU          (assoc (gp/geographic-position  -34.000  151.000) :name "Sydney, Australia"))
(def Tananarive-MG      (assoc (gp/geographic-position  -18.833   47.550) :name "Tananarive, Madagascar"))
(def Teheran-IR         (assoc (gp/geographic-position   35.750   51.750) :name "Teheran, Iran"))
(def Tokyo-JP           (assoc (gp/geographic-position   35.667  139.750) :name "Tokyo, Japan"))
(def Venice-IT          (assoc (gp/geographic-position   45.433   12.333) :name "Venice, Italy"))
(def Veracruz-MX        (assoc (gp/geographic-position   19.167  -96.167) :name "Veracruz, Mexico"))
(def Vienna-AT          (assoc (gp/geographic-position   48.233   16.333) :name "Vienna, Austria"))
(def Vladivostok-RU     (assoc (gp/geographic-position   43.167  132.000) :name "Vladivostok, Russia"))
(def Warsaw-PL          (assoc (gp/geographic-position   52.233   21.000) :name "Warsaw, Poland"))
(def Wellington-NZ      (assoc (gp/geographic-position  -41.283  174.783) :name "Wellington, New Zealand"))
(def Zurich-CH          (assoc (gp/geographic-position   47.350    8.517) :name "Zurich, Switzerland"))

;;; Observatories
(def aao (assoc (gp/geographic-position -31.2753833333333 149.067) :name "Australian Astronomical Observatory, Australia"))
(def aip (assoc (gp/geographic-position 52.405 13.104) :name "Leibniz-Institut für Astrophysik Potsdam, Germany"))
(def ali (assoc (gp/geographic-position 32.326 80.026) :name "Ali Observatory, China"))
(def alma (assoc (gp/geographic-position -23.029 -67.755) :name "Atacama Large Millimeter Array, Chile"))
(def apex (assoc (gp/geographic-position -23.011 -67.779) :name "Atacama Pathfinder Experiment, Chile"))
(def apo (assoc (gp/geographic-position 52.354 4.955) :name "Apache Point Observatory, United States"))
(def arecibo (assoc (gp/geographic-position 18.2 -66.40) :name "Arecibo Observatory, Puerto Rico"))
(def armagh (assoc (gp/geographic-position 54.352 -6.648) :name "Armagh Observatory, United Kingdom"))
(def asiago (assoc (gp/geographic-position 45.867 11.526) :name "Osservatorio Astrofisico di Asiago"))
(def atca (assoc (gp/geographic-position -30.313 149.565) :name "Australia Telescope Compact Array"))
(def bao (assoc (gp/geographic-position 40.396 117.576) :name "Beijing XingLong Observatory, China"))
(def biruni (assoc (gp/geographic-position 29.650 52.505) :name "Biruni Observatory, Iran"))
(def calan (assoc (gp/geographic-position -33.396 -70.536) :name "Observatorio Astronómico Nacional de Chile, Chile"))
(def calaralto (assoc (gp/geographic-position 37.224 -2.546) :name "Calar Alto, Spain"))
(def cao (assoc (gp/geographic-position 44.724 34.010) :name "Crimean Astrophysical Observatory, Ukraine"))
(def casleo (assoc (gp/geographic-position -31.799 -69.296) :name "Leoncito Astronomical Complex, Argentina"))
(def cfht (assoc (gp/geographic-position 19.825 -155.469) :name "Canada-France-Hawaii Telescope, United States"))
(def ctio (assoc (gp/geographic-position -30.169 -70.806) :name "Cerro Tololo Interamerican Observatory, Chile"))
(def dao (assoc (gp/geographic-position 48.520 -123.418) :name "Dominion Astrophysical Observatory, Canada"))
(def dct (assoc (gp/geographic-position 34.744 -111.423) :name "Discovery Channel Telescope, United States"))
(def drao (assoc (gp/geographic-position 49.322 -119.620) :name "Dominion Radio Astrophysical Observatory, Canada"))
(def dwingeloo (assoc (gp/geographic-position 52.812 6.396) :name "Dwingeloo Radio Observatory, Netherlands"))
(def effelsberg (assoc (gp/geographic-position 50.525 6.883) :name "Effelsberg 100m telescope, Germany"))
(def ekar (assoc (gp/geographic-position 45.849 11.569) :name "Mount Ekar 182 cm. Telescope, Italy"))
(def elt (assoc (gp/geographic-position -24.589 -70.192) :name "European Extremely Large Telescope, Chile"))
(def fast (assoc (gp/geographic-position 25.653 106.857) :name "500m-aperture Spherical Telescope, China"))
(def flwo (assoc (gp/geographic-position 31.681 -110.878) :name "Whipple Observatory, United States"))
(def gbo (assoc (gp/geographic-position 38.433 -79.840) :name "Green Bank Observatory, United States"))
(def gemn (assoc (gp/geographic-position 19.824 -155.469) :name "Gemini North, United States"))
(def gems (assoc (gp/geographic-position -30.241 -70.737) :name "Gemini South, Chile"))
(def griffith (assoc (gp/geographic-position 34.119 -118.300) :name "Griffith Observatory, United States"))
(def haleakala (assoc (gp/geographic-position 20.708 -156.257) :name "Haleakala Observatories, United States"))
(def halley (assoc (gp/geographic-position -15.962 -5.699) :name "Halley's Mount, Saint Helena"))
(def hanford (assoc (gp/geographic-position 46.455 -119.408) :name "LIGO (Hanford), United States"))
(def heto (assoc (gp/geographic-position 39.486 -74.553) :name "Harold E. Taylor Observatory, United States"))
(def iao (assoc (gp/geographic-position 32.779 78.964) :name "Indian Astronomical Observatory, India"))
(def icao (assoc (gp/geographic-position 37.693 14.974) :name "INAF Catania Astrophysical Observatory, Italy"))
(def igo (assoc (gp/geographic-position 19.073 73.845) :name "IUCAA Girawali Observatory, India"))
(def ilmt (assoc (gp/geographic-position 29.361 79.684) :name "International Liquid Mirror Telescope   India"))
(def iram (assoc (gp/geographic-position 37.066 -3.392) :name "IRAM 30m telescope, Spain"))
(def irtf (assoc (gp/geographic-position 19.826 -155.472) :name "NASA Infrared Telescope Facility, United States"))
(def ishigaki (assoc (gp/geographic-position 24.373 124.139) :name "Ishigaki Astronomical Observatory, Japan"))
(def jcmt (assoc (gp/geographic-position 19.823 -155.477) :name "James Clerk Maxwell Telescope, United States"))
(def jena (assoc (gp/geographic-position 50.925 11.583) :name "Jena Observatory, Germany"))
(def jodrell (assoc (gp/geographic-position 53.237 -2.309) :name "Jodrell Bank Observatory, United Kingdom"))
(def keck (assoc (gp/geographic-position 19.826 -155.474) :name "W. M. Keck Observatory, United States"))
(def kiso (assoc (gp/geographic-position 35.797 137.625) :name "Kiso Observatory, Japan"))
(def kpno (assoc (gp/geographic-position 31.963 -111.600) :name "Kitt Peak National Observatory, United States "))
(def lapalma (assoc (gp/geographic-position 28.761 -17.882) :name "Roque de los Muchachos, La Palma, Spain"))
(def lasilla (assoc (gp/geographic-position -29.259 -70.734) :name "La Silla Observatory (ESO), Chile"))
(def lbt (assoc (gp/geographic-position 32.702 -109.889) :name "Large Binocular Telescope, United States"))
(def lco (assoc (gp/geographic-position -29.014 -70.693) :name "Las Campanas Observatory, Chile"))
(def lhk (assoc (gp/geographic-position 49.398 8.725) :name "Landessternwarte Heidelberg-Königstuhl, Germany"))
(def lick (assoc (gp/geographic-position 37.343 -121.637) :name "Lick Observatory, United States"))
(def livingston (assoc (gp/geographic-position 30.563 -90.774) :name "LIGO (Livingston), United States"))
(def lmt (assoc (gp/geographic-position 18.986 -97.315) :name "Large Millimeter Telescope, Mexico"))
(def loiano (assoc (gp/geographic-position 44.259 11.334) :name "Loiano Observatory, Italy"))
(def lowell (assoc (gp/geographic-position 35.097 -111.535) :name "Lowell Observatory, United States"))
(def mcdonald (assoc (gp/geographic-position 30.672 -104.022) :name "McDonald Observatory, United States"))
(def mdm (assoc (gp/geographic-position 31.953 -111.615) :name "Michigan-Dartmouth-MIT Observatory, United States"))
(def medicina (assoc (gp/geographic-position 44.521 11.647) :name "Medicina Radio Telescope, Italy"))
(def metsahovi (assoc (gp/geographic-position 60.218 24.393) :name "Metsähovi Radio Observatory, Finland"))
(def midi (assoc (gp/geographic-position 42.937 0.141) :name "Observatoire du Pic du Midi, France"))
(def miro (assoc (gp/geographic-position 24.653 72.780) :name "Mount Abu InfraRed Observatory, India"))
(def mmt (assoc (gp/geographic-position 31.688 -110.885) :name "Multiple Mirror Telescope, United States"))
(def molonglo (assoc (gp/geographic-position -35.371 149.428) :name "Molonglo Observatory Synthesis Telescope, Australia"))
(def mrao (assoc (gp/geographic-position -26.697 116.631) :name "Murchison Radio-astronomy Observatory, Australia"))
(def mro (assoc (gp/geographic-position 46.951 -120.725) :name "Manastash Ridge Observatory, United States"))
(def mtbigelow (assoc (gp/geographic-position 32.417 -110.732) :name "Catalina Observatory: 61 inch telescope, United States"))
(def mullard (assoc (gp/geographic-position 52.167 0.033) :name "Mullard Radio Astronomy Observatory, United Kingdom"))
(def mwo (assoc (gp/geographic-position 34.226 -118.057) :name "Mount Wilson Observatory, United States"))
(def ngts (assoc (gp/geographic-position -24.616 -70.391) :name "Next-Generation Transit Survey, Chile"))
(def nhao (assoc (gp/geographic-position 35.025 134.335) :name "Nishi-Harima Astronomical Observatory, Japan"))
(def nobeyama (assoc (gp/geographic-position 35.945 138.472) :name "Nobeyama 45m Telescope, Japan"))
(def noto (assoc (gp/geographic-position 36.876 14.989) :name "Noto Radio Telescope, Italy"))
(def nov (assoc (gp/geographic-position 8.787 -70.870) :name "National Observatory of Venezuela, Venezuela"))
(def oaj (assoc (gp/geographic-position 40.042 -1.016) :name "Observatorio Astrofísico de Javalambre, Spain"))
(def oanc (assoc (gp/geographic-position 4.640 -74.083) :name "Observatorio Astronómico Nacional de Colombia, Colombia"))
(def oao (assoc (gp/geographic-position 34.577 133.594) :name "Okayama Astrophysical Observatory, Japan"))
(def oavda (assoc (gp/geographic-position 45.790 7.478) :name "Val d'Aosta Observatory, Italy"))
(def oca (assoc (gp/geographic-position 43.727 7.299) :name "Observatoire de de la Côte d’Azur, France"))
(def ohp (assoc (gp/geographic-position 43.931 5.713) :name "Observatoire de Haute Provence, France"))
(def olin (assoc (gp/geographic-position 41.379 -72.105) :name "Olin Science Center, United States"))
(def oliver (assoc (gp/geographic-position 36.306 -121.567) :name "Oliver Observing Station, United States"))
(def onsala (assoc (gp/geographic-position 57.393 11.918) :name "Onsala Space Observatory, Sweden"))
(def palomar (assoc (gp/geographic-position 33.356 -116.863) :name "Palomar Observatory, United States"))
(def paranal (assoc (gp/geographic-position -24.628 -70.405) :name "Paranal Observatory (ESO), Chile"))
(def parkes (assoc (gp/geographic-position -32.998 148.263) :name "Parkes 64m Telescope, Australia"))
(def pdb (assoc (gp/geographic-position 44.634 5.908) :name "Plateau de Bure Interferometer, France"))
(def pddo (assoc (gp/geographic-position -22.535 -45.583) :name "Observatório Pico dos Dias, Brazil"))
(def peyton (assoc (gp/geographic-position 40.347 -74.652) :name "Peyton Observatory, United States"))
(def pulkovo (assoc (gp/geographic-position 59.772 30.326) :name "Pulkovo Observatory, Russia"))
(def roanjase (assoc (gp/geographic-position -33.717 -70.331) :name "Los Nogales de Roan Jase, Chile"))
(def roe (assoc (gp/geographic-position 55.923 -3.188) :name "Royal Observatory, Edinburgh, United Kingdom"))
(def rog (assoc (gp/geographic-position 51.478 -0.001) :name "Royal Observatory Greenwich, United Kingdom"))
(def rozhen (assoc (gp/geographic-position 41.693 24.739) :name "Bulgarian National Astronomical Observatory"))
(def salt (assoc (gp/geographic-position -32.376 20.811) :name "Southern African Large Telescope, South Africa"))
(def saoras (assoc (gp/geographic-position 43.647 41.440) :name "Special Astrophysical Observatory, Russia"))
(def sirene (assoc (gp/geographic-position 44.000 5.487) :name "Observatoire Sirene, France"))
(def ska (assoc (gp/geographic-position -30.722 21.411) :name "Square Kilometre Array, South Africa"))
(def skinakas (assoc (gp/geographic-position 35.212 24.899) :name "Skinakas Observatory, Greece"))
(def sma (assoc (gp/geographic-position 19.824 -155.479) :name "Submillimeter Array, United States"))
(def southam (assoc (gp/geographic-position 49.275 -123.144) :name "Gordon Southam Observatory, Canada"))
(def spm (assoc (gp/geographic-position 31.044 -115.464) :name "Observatorio Astronomico Nacional, San Pedro Martir, Mexico"))
(def spt (assoc (gp/geographic-position -90.000 180.000) :name "South Pole Telescope"))
(def srt (assoc (gp/geographic-position 39.493 9.245) :name "Sardinia Radio Telescope, Italy"))
(def subaru (assoc (gp/geographic-position 19.826 -155.476) :name "Subaru Telescope, United States"))
(def teide (assoc (gp/geographic-position 28.301 -16.511) :name "Teide Observatory, Spain"))
(def tno (assoc (gp/geographic-position 18.574 98.482) :name "Thai National Observatory, Thailand"))
(def tona (assoc (gp/geographic-position 19.032 -98.316) :name "Observatorio Astronomico Nacional, Tonantzintla, Mexico"))
(def uclo (assoc (gp/geographic-position 51.613 -0.242) :name "University College London Observatory, United Kingdom"))
(def ucmjo (assoc (gp/geographic-position -43.985 170.465) :name "University of Canterbury Mount John Observatory, New Zealand"))
(def ufrj (assoc (gp/geographic-position -22.899 -43.187) :name "Observatório do Valongo, Brazil"))
(def vbo (assoc (gp/geographic-position 12.575 78.820) :name "Vainu Bappu Observatory, India"))
(def venus (assoc (gp/geographic-position -17.494 -149.494) :name "Pointe Vénus, French Polynesia"))
(def vidojevica (assoc (gp/geographic-position 43.141 21.556) :name "Astronomical Station Vidojevica, Serbia"))
(def vienna (assoc (gp/geographic-position 48.232 16.334) :name "Vienna Observatory, Austria"))
(def vista (assoc (gp/geographic-position -24.616 -70.398) :name "VISTA, Chile"))
(def vla (assoc (gp/geographic-position 34.079 -107.618) :name "Very Large Array, United States"))
(def wendelstein (assoc (gp/geographic-position 47.704 12.012) :name "Wendelstein Observatory, Germany"))
(def wise (assoc (gp/geographic-position 30.597 34.762) :name "Wise Observatory, Israel"))
(def wright (assoc (gp/geographic-position 54.674 -1.629) :name "Wright's Tower, United Kingdom"))



(defn get-name [l]
  (:name l))

(defn to-string 
  "A standard java to-string for a location."
  [l]
  (str (get-name l) ": " (gp/get-latitude l) ", " (gp/get-longitude l)))
 
(defn list-locations 
  "Alphabetical list of all available locations."
  []
  (sort (keys (ns-interns 'geoutils.locations))))

